### PR TITLE
setup.dm now includes Docker option; fix #167

### LINKED ISSUE #167: containerized setup
Hi, I containerized the setup (jupyter lab, dependencies, and data). Please let me know if it is of interest that I (by pull request) contribute it as an alternative setup to the current options.

### PR DESCRIPTION
**Pull request by joh4nd**
I added to `setup.md` a short docker setup.

I also numbered the prior instructions such that it was easier to figure out the steps, and to jump to option 2. docker if desired.

### CODE REVIEW

**Comment by joh4nd** [comment]
Hi @rbavery, pinging you in case you have not seen this suggestion. Cheers

**Comment by rbavery** [comment]
From my past experience teaching these workshops, most learners are grad students or others in academia who aren't familiar with docker. I lean toward not including these instructions in the setup page in order to minimize confusion for them, but I'm happy to refer to these instructions outside of the site. Maybe in a separate readme in this repo and folks who are examining the github looking for a Dockerfile might find it useful.

I'm also curious what other folks think, especially if they have taught this workshop. Would these instructions be helpful in a workshop setting @fnattino @rogerkuou ?

**Comment by rogerkuou** [comment]
Thanks @joh4nd for the contribution! And thanks @rbavery for the initial review.

I tend to agree with @rbavery that Docker is too advanced for most of our audience. 

I have a worry for DOCKER from my side. Based on my teaching experience, most of the workshop audience who have setup problems are organization laptop users who do not have admin rights on their device. I think DOCKER might be a problem here.

On the other hand, a lot of students, especially WINDOWS users, use Anaconda. And the current solution is the least confusing one for them.

**Comment by rbavery** [comment]
I'm going to close this since I think folks who have taught this are in agreement. Thank you for sharing it though @joh4nd.

**Pull request closed without merging**
