### PR TITLE
Add lesson 12

### PR DESCRIPTION
**Pull request by alex-pakalniskis**
Update Lesson 12 with Python code

### CODE REVIEW

**Comment by rbavery** [comment]
Hey @alex-pakalniskis ! Thanks a bunch for contributing this lesson. I'm a tad embarrassed to say that I just now noticed this PR! Reviewing it right now. We recently taught a few episodes of this workshop to the NASA DEVELOP program and it looks like this would make a great addition that would be useful to them and others in the future.

**Comment by alex-pakalniskis** [comment]
Happy to help. And no worries. 2020 has been hectic. Let me know if I can help otherwise too.

**Comment by rbavery** [comment]
Awesome @alex-pakalniskis 

Would you mind checking the box that says "Allow edits from maintainers"? https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I went through and made changes in a commit but then realized I don't have commit access on this PR. Most of the changes are path updates, some explanation edits, removing refs to R, and fixing challenge formatting.

I think it's good to be taught once that is merged, but I'll still leave it open, the one outstanding issue is to include plot outputs and code outputs in the challenge solution to show learners what the solution should look like. After I get commit access and push my commit, would you want to include those challenge outputs?

**Comment by alex-pakalniskis** [comment]
It's already checked. Not sure if I need to change another setting on my end. Included screenshot (hope it shows).
I can definitely work on those challenges this weekend. 

image

**Comment by rbavery** [comment]
Got it! had to associate my branch I made from the PR with your fork with ` git branch -u alex-p/gh-pages` before pushing with `git push alex-p HEAD:gh-pages`. I think it's probably easier in the future for me to clone your fork and push to the branch directly, for my own future reference.

Thanks a bunch again, I can review those changes when they come by.

**Comment by rbavery** [comment]
Thanks @alex-pakalniskis ! Can you include the result plots in the challenge solution so that they are embedded in the solution drop down? Earlier episodes with challenges have some examples for what this looks like in markdown.

**Comment by alex-pakalniskis** [comment]
No worries @rbavery. On my end, none of the plots render for any challenge section. I tried to follow the markdown syntax as best I could, so I'm not actually sure how to remedy this.

**Comment by rbavery** [comment]
@alex-pakalniskis no worries, and sorry there was some rendering trouble. I added the plots and they render on my end (I'm using chrome, maybe it's a browser issue?)

I used this syntax to insert plots
`plot of phenology points and points`

This looks good to me so I've merging. Thanks a bunch for your help!

**Comment by alex-pakalniskis** [comment]
Thanks! Makes sense it's just a bit of HTML. Sorry I missed that code chunk in previous lessons. Thanks for fixing it.

**Pull request merged**
